print ("Hello, World!")
name = input("Enter your name: ")
print("Hello + name")
print(f"Hello {name}")
age = int(input("Enter your age: "))
print(f"Hello, {name}! You are {age} years old.")
print(f"Next year you will be {age + 1} years old.")